//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBoutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int idArticle { get; set; }
        public string refArticle { get; set; }
        public string libelleArticle { get; set; }
        public Nullable<double> prix { get; set; }
        public string description { get; set; }
        public Nullable<bool> disponibilite { get; set; }
        public Nullable<int> nbpieces { get; set; }
        public string couleur { get; set; }
        public string taille { get; set; }
        public string cheminImage { get; set; }
        public Nullable<int> idCategorie { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<int> idMarque { get; set; }
        public Nullable<int> idAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Marque Marque { get; set; }
        public virtual Type Type { get; set; }
    }
}
